### ISSUE TITLE
Pretrained file bevfusion2 missing on google drive

### ISSUE THREAD

**Issue by gabriel-tjio** [Bob-cheng/CL-FusionAttack#4]
Dear Bob,

thanks very much for sharing your code and your excellent work.
I tried accessing the pretrained file for bevfusion2, but it seems to have been removed.
Is there another location where I can download the file?

Best regards,
Gabriel

**Comment by Ian-Tam** [comment]
@gabriel-tjio Hello, did you find the ckpt for bevfusion2?
